### PR TITLE
Make Socket.tcp arglist compatible with core version (fixes #32)

### LINKED ISSUE #32: FTP connections raise ArgumentError: wrong number of arguments (given 2, expected 3)
### Steps to reproduce problem

```ruby
>> require 'tcr'
=> true
>> require 'net/ftp'
=> true
>> Net::FTP.open('root.cern.ch')
ArgumentError: wrong number of arguments (given 2, expected 3)
from ~/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/tcr-0.2.0/lib/tcr.rb:91:in `tcp'
```

(This error does not occur if you do not `require 'tcr'` first.)

### The problem

TCR's monkey-patched `Socket.tcp` requires a different set of arguments from Ruby's built-in `Socket.tcp`:

```ruby
# lib/ruby/2.5.0/socket.rb
def self.tcp(host, port, local_host = nil, local_port = nil, connect_timeout: nil)

# tcr/lib/tcr.rb
class Socket
  class << self
    def tcp(host, port, socket_opts)
```

### Proposed solution

The `socket_opts` argument (not used by TCR, and passed directly to `Socket.tcp` for non-watched ports) should be modified to be optional / support multiple arguments with the splat operator (`*`):

```ruby
def tcp(host, port, *socket_opts)
```

I'll submit a PR shortly.

### PR DESCRIPTION
**Pull request by rlue**

### CODE REVIEW

**Comment by robforman** [comment]
good stuff- I'll take a look

File: spec/tcr_spec.rb [hunk 1]
```diff
@@ -440,7 +440,7 @@
     }
 
     TCR.use_cassette("test") do
-      sock = Socket.tcp("towel.blinkenlights.nl", 23, {})
+      sock = Socket.tcp("towel.blinkenlights.nl", 23)
       expect(sock).to be_a(TCR::RecordableTCPSocket)
     end
```
Comment (robforman) [inline spec/tcr_spec.rb]: If this spec uses a cassette named "test"... does that mean a new cassette file should be checked in as well? Is there a chance it didn't record or isn't behaving how we think?

Comment (rlue) [reply spec/tcr_spec.rb]: Thanks for the follow-up!

My understanding is that the whole spec is written to 1) delete any existing `test.xxx` cassette files before each example, 2) record a new cassette in each example, and then 3) delete the newly recorded cassette after each example (per [this `around` block](https://github.com/robforman/tcr/blob/72fa8427350c2968871afd66c88cfc094b068743/spec/tcr_spec.rb#L17-L25))

In either case, the success or failure of the cassette recording isn't quite the focus here: rather, the change here is to ensure that `Socket.tcp` does not strictly **require** three arguments (because Ruby's STDLIB `Socket.tcp` only requires two).

Before this PR, removing the `{}` would have caused the test to fail (`ArgumentError`); with this PR, you can remove it, and the test will still pass. Thus, the presence of a cassette file (or any problems saving a new recording) make no difference to the fidelity of the test.
