### PR TITLE
Check path existence / file permissions for cassette file (fixes #28)

### LINKED ISSUE #28: TCR fails if path to cassette does not exist
For instance,

```ruby
>> TCR.configure do |c|
>*   c.cassette_library_dir = 'nonexistent/path'
>* end
=> "nonexistent/path"
>> TCR.use_cassette('test') { }
Errno::ENOENT: No such file or directory @ rb_sysopen - nonexistent/path/test.json
```

(I'm submitting a PR for this momentarily.)

### PR DESCRIPTION
**Pull request by rlue**
Also includes some indentation / trailing whitespace / formatting fixes to spec file.

### CODE REVIEW

File: lib/tcr/cassette.rb [hunk 1]
```diff
@@ -1,22 +1,23 @@
...
-        @recording = false
-        @contents = File.open(filename) { |f| f.read }
-        @sessions = unmarshal(@contents)
-      else
-        @recording = true
+      if recording?
+        verify_cassette_path_is_writable
         @sessions = []
+      else
+        @sessions = unmarshal(File.read(filename))
```
Comment (robforman) [inline lib/tcr/cassette.rb]: I don't quite follow the flow above.

First you use the ternary to set sessions to blank "if `recording?` .. then you if/else it again, which sets sessions to empty array again.. or unmarshal's it again.

Can you you help me understand?

And `recording?` seems inverted.. since you added `!File.exists`

File: spec/tcr_spec.rb [hunk 2]
```diff
@@ -6,7 +6,7 @@
 require "net/smtp"
 require "net/ldap"
 require "tcr/net/ldap"
-require 'thread'
+require "thread"
```
Comment (robforman) [inline spec/tcr_spec.rb]: unused?

File: lib/tcr/cassette.rb (hunk 1 above)
Comment (rlue) [reply lib/tcr/cassette.rb]: Whoops, 100% mistake :sweat:.

1. Pushed a fix last week, but forgot to follow up on this thread.

2. > And `recording?` seems inverted.. since you added `!File.exists`

   The original stanza was

   ```ruby
   if File.exists?(filename)
     @recording = false
     @contents = File.open(filename) { |f| f.read }
     @sessions = unmarshal(@contents)
   else
     @recording = true
     @sessions = []
   end
   ```

   Thus, if the file doesn't exist, we're `@recording` and `@sessions` is set to an empty array. The logic looks identical to me (but maybe I'm missing something?).

3. One catch that I just noticed is with the `||=` operator in my version of the `#recording?` method:

   ```ruby
   def recording?
     @recording ||= !File.exists?(filename)
   end
   ```

   If the file _does_ exist, this will call `File.exists?` every time it's called, since a `false` value for `@recording` will cause the rest of the expression to be evaluated. However, I think that the performance cost will be entirely negligible, and the added readiability is worth it.

**Comment by rlue** [comment]
Hey @robforman, what's the status of this PR? Anything I can do to help get it merged?

**Comment by robforman** [comment]
Sorry- was traveling. No, it looks great.
